### ISSUE TITLE
Applicative wrapping another applicative

### ISSUE THREAD

**Issue by FrankHB** [jhidding/scarlett#1]
`Applicative::wrap` in `combiners.h` `return this` directly. Is that intentional?

Note R<sup>-1</sup>RK allows nested applicatives explicitly.

**Comment by jhidding** [comment]
Its a way of having both applicative and operative combiners follow the same abstract C++ interface. It's a while ago I worked on this; at some point I diverged form R⁻¹RK. For example, I don't fully understand how the exception mechanism is supposed to work, and I never got round to implementing the numerical tower in a sensible way. Concerning wrap and unwrap, I'm guessing here, I thought it made more sense this way.

**Comment by FrankHB** [comment]
I see. Thanks for clarification.
